<?php
/**
 * Created by tiway
 * Date: 2017/9/27
 * Time: 15:58
 */

namespace app\mobile\controller;


use app\common\controller\MobileBase;
use think\Exception;

class Article extends MobileBase
{

    private $article_read,$article_deleted,$article_sys,$article_integral,$article_help;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->article_read     = 'read';
        $this->article_deleted  = 'deleted';
        $this->article_sys      = 1;//系统信息
        $this->article_integral = 2;//积分机制
        $this->article_help     = 3;//帮助中心

    }

    /**
     * 系统信息/帮助中心/头条信息 文章详情
     * @param $article_id
     */
    public function article_detail($api = false){
        if(request()->isGet()){
            try{
                $article_id = input('article_id');
                if(empty($article_id))
                    throw new Exception('操作失败');

                $article = model('Article')
                    ->field('title,content,create_time')
                    ->find($article_id);
                if(empty($article))
                    throw new Exception('未找到对应文章');

                if($api){
                   return json(apiSuccess($article));
                }else{
                    return view(['data'=>$article]);
                }
            }catch(\Exception $e){
                if($api){
                    return json(apiFail($e->getMessage()));
                }else{
                    return view(['msg'=>$e->getMessage()]);
                }
            }
        }

    }
    
    /**
     * @desc 读系统信息
     * @param bool $api
     * @return \think\response\Json|\think\response\View
     */
    public function article_msg($api = false){
        if(request()->isGet()){
            try{
                if(empty($this->user_id))
                    return json(apiSessionFail());

                $article_id = input('article_id');
                if(empty($article_id))
                    throw new Exception('操作失败');

                //文章信息
                $article = model('Article')
                    ->field('title,content,create_time')
                    ->find($article_id);
                if(empty($article))
                    throw new Exception('未找到对应文章');

                //修改已读
                model('MessageStatus')->save(['user_id'=>$this->user_id,'article_id'=>$article_id,'status'=>'read']);

                if($api){
                    return json(apiSuccess($article));
                }else{
                    return view(['data'=>$article]);
                }
            }catch(\Exception $e){
                if($api){
                    return json(apiFail($e->getMessage()));
                }else{
                    return view(['msg'=>$e->getMessage()]);
                }
            }
        }

    }

    /**
     * @desc 系统信息
     * @param int $type
     */
    public function msg_system($api = false){
        if(request()->isGet()){
            try{
                if(empty($this->user_id))
                    return json(apiSessionFail());

                $type = input('type',1);
                if($type == 1){#已读信息
                    $read_article = model('MessageStatus')
                        ->where(['user_id'=>$this->user_id,'status'=>$this->article_read])
                        ->column('article_id');

                    $ids = array_unique($read_article);
                    $articles = model('article')
                        ->field('id,title,content,create_time')
                        ->where('type_id',$this->article_sys)
                        ->where('id','in',$ids)
                        ->select();

                }elseif ($type == 2){#未读信息
                    $read_article = model('MessageStatus')
                        ->where(['user_id'=>$this->user_id])
                        ->column('article_id');

                    $articles = model('article')
                        ->field('id,title,content,create_time')
                        ->where('type_id',$this->article_sys)
                        ->where('id','notin',$read_article)
                        ->select();

                }

                if($api){
                    return json(apiSuccess($articles));
                }else{
                    return view(['article'=>$articles]);
                }

            }catch (\Exception $e){
                if($api){
                    return json(apiFail($e->getMessage()));
                }else{
                    return view(['msg'=>$e->getMessage()]);
                }
            }
        }

    }


    /**
     * @desc 帮助中心列表
     * @param bool $api
     * @return \think\response\Json|\think\response\View
     */
    public function msg_help($api = false){
        if(request()->isGet()){
            try{
                $articles = model('article')
                    ->field('id,title,create_time')
                    ->where('type_id',$this->article_help)
                    ->select();

                if($api){
                    return json(apiSuccess($articles));
                }else{
                    return view(['article'=>$articles]);
                }

            }catch (\Exception $e){
                if($api){
                    return json(apiFail($e->getMessage()));
                }else{
                    return view(['msg'=>$e->getMessage()]);
                }
            }
        }
    }

    /**
     * @desc 积分机制
     * @param bool $api
     * @return \think\response\Json|\think\response\View
     */
    public function msg_integral($api = false){
        if(request()->isGet()){
            try{
                $articles = model('article')
                    ->field('id,title,content,create_time')
                    ->where('type_id',$this->article_integral)
                    ->order('create_time desc')
                    ->find();

                if($api){
                    return json(apiSuccess($articles));
                }else{
                    return view(['article'=>$articles]);
                }

            }catch (\Exception $e){
                if($api){
                    return json(apiFail($e->getMessage()));
                }else{
                    return view(['msg'=>$e->getMessage()]);
                }
            }
        }
    }

}