<?php
/**
 * Created by tiway
 * Date: 2017/9/29
 * Time: 14:26
 */

namespace app\mobile\controller;


use app\common\controller\MobileBase;
use think\Exception;

class Comment extends MobileBase
{
    private $attr_capacity,$attr_color;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->attr_capacity = 3;//容量
        $this->attr_color    = 2;//颜色


    }

    /**
     * @desc 评论列表
     * @param bool $api
     * @return \think\response\Json
     *
     */
    public function comment_list($api = false){
        if(request()->isPost()){
            try{
                //每页条数
                $per_page = input('per_page','5');
                //第几页，默认第一页
                $page  = input('page','1');

                $goods_id = input('goods_id');
                if(empty($goods_id))
                    throw new Exception("参数错误");
                //评价标签，好评率
                $goods = model('Goods')
                    ->field('goods_id,goods_name,praise_percentage,evaluate')
                    ->find($goods_id);
                //评论列表
                $comments = model('GoodsComment')
                    ->field('U.nickname,U.photo,GC.goods_id,GC.price_id,GC.user_id,GC.comment,GC.com_img1,GC.com_img2,GC.com_img3,GC.com_img4,GC.com_img5,GC.create_time,GP.attrs_values')
                    ->alias('GC')
                    ->join('ui_goods_price GP ',' GC.price_id = GP.id')
                    ->join('ui_user U ',' U.user_id = GC.user_id')
                    ->where('GC.goods_id',$goods_id)
                    ->order('GC.create_time desc')
                    ->limit($per_page)
                    ->page($page)
                    ->select();
                foreach ($comments as &$value){
                    $value['attrs_values'] = model('Goods')->get_four_attr($value['attrs_values']);
                }
                $data = array(
                    'goods'     => $goods,
                    'comments'  => $comments
                );

                return json(apiSuccess($data));

            }catch (\Exception $e){

                return json(apiFail($e->getMessage()));

            }


        }
    }

    public function comment_detail($api = false){
        if(request()->isPost()){
            try{
                $order_id = input('order_id');
                $goods_id = input('goods_id');
                if(empty($order_id) || empty($goods_id))
                    throw new Exception('参数错误');

                $order_info = model('OrderInfo')
                    ->field('order_id,goods_id,price_id,goods_name,good_image,good_attr,goods_count,price,has_comment,create_time')
                    ->with(['order'=>function($query){
                        $query->field('order_id,order_sn,total_price,deal_price');
                    }])
                    ->where(['order_id'=>$order_id,'goods_id'=>$goods_id])->find();
                if(empty($order_info))
                    throw new Exception('网络错误');
                $order_info['good_attr'] = unserialize($order_info['good_attr']);

                if($api){
                    return json(apiSuccess($order_info));
                }else{
                    return view(['order_info'=>$order_info]);
                }
            }catch (\Exception $e){
                if($api){
                    return json(apiFail($e->getMessage()));
                }else{
                    return view(['msg'=>$e->getMessage()]);
                }
            }
        }
    }
}