<?php
/**
 * Created by tiway
 * Date: 2017/9/25
 * Time: 18:08
 */

namespace app\mobile\controller;


use app\common\controller\MobileBase;

class Index extends MobileBase
{
    private $article_integral,$article_headline;
    private $attr_color,$attr_condition,$attr_capacity;
    private $store_fan,$store_special,$store_recommend;
    private $comment_good,$comment_mid,$comment_bad;

    private $banner_top,$banner_mid;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

        $this->attr_color       = 2;//颜色属性
        $this->attr_condition   = 4;//成色属性
        $this->attr_capacity    = 3;//成色属性

        $this->article_integral = 2;//积分类型
        $this->article_headline = 4;//积分类型

        $this->store_fan       = 1;//发烧友专区
        $this->store_special   = 2;//特价专区
        $this->store_recommend = 3;//推荐专区

        $this->banner_top = 1;//首页头部banner
        $this->banner_mid = 2;//首页头部banner

        $this->comment_good = 3;//好评
        $this->comment_mid  = 2;//中评
        $this->comment_bad  = 1;//差评

    }

    public function index($api = false){
        //头部banner
        $banner_tops = model('Banner')
            ->field('id,title,banner')
            ->where('type_id',$this->banner_top)
            ->where('is_using','Y')
            ->select();

        //头条
        $headlines = model('Article')
            ->field('id,title')
            ->where('type_id',$this->article_headline)
            ->order('create_time desc')
            ->limit(10)
            ->select();


        //发烧友专区
        $fans = model('Goods')
            ->field('goods_id,goods_name,goods_thums,sale_count,praise_percentage')
            ->with(['goodsPrice'=>function($query){
                $query->field('id as price_id,goods_id,campaign_price,price,attrs_values');
            }])
            ->where('store_id',$this->store_fan)
            ->order('create_time desc')
            ->limit(4)
            ->select();
        $fans = model('Goods')->get_attr_goods($fans);


        //中部banner
        $banner_mids = model('Banner')
            ->field('id,title,banner')
            ->where('type_id',$this->banner_mid)
            ->where('is_using','Y')
            ->order('create_time desc')
            ->find();

        //好评展示
        $comments = model('Goods')
            ->field('goods_id,praise_percentage')
            ->with(['comments'=>function($query){
                $query->field('goods_id,comment_id,user_id,comment,create_time')
                    ->where('score',3)
                    ->where('comment','not null')
                    ->with(['user'=>function($query){
                        $query->field('user_id,photo');
                    }])
                    ->order('create_time desc')
                   ;
            }])
            ->order('praise_percentage desc')
            ->where('praise_percentage','<>','0')
            ->limit(10)
            ->select();
        $good_comments = array();
        foreach ($comments as $key =>$comment){
            $good_comments[$key]['praise_percentage'] = $comment->praise_percentage;
            if(isset($comment->comments[0])){
                $good_comments[$key]['user_phone'] = $comment->comments[0]->user->photo;
                $good_comments[$key]['comment'] = $comment->comments[0]->comment;
            }

        }

        //特价卖场
        $specials = model('Goods')
            ->field('goods_id,goods_name,goods_thums,sale_count,praise_percentage')
            ->with(['goodsPrice'=>function($query){
                $query->field('id as price_id,goods_id,campaign_price,price,attrs_values');
            }])
            ->where('store_id',$this->store_special)
            ->order('create_time desc')
            ->limit(4)
            ->select();
        $specials = model('Goods')->get_attr_goods($specials);

        //消费记录
        $records = model('Order')
            ->field('user_id,order_id')
            ->with([
                'user'=>function($query){
                $query->field('user_id,nickname');
            },
                'orderInfo'=>function($query){
                    $query->field('order_id,goods_name,good_attr');
            }
            ])
            ->order('create_time desc')
            ->limit(10)
            ->select();
        $sale_records = array();
        foreach ($records as $key => $record){
            $sale_records[$key]['nickname'] = $record->user->nickname;
            $sale_records[$key]['goods_name'] = $record->orderInfo[0]->goods_name;
            $attr = unserialize($record->orderInfo[0]->good_attr);
            unset($attr[1]);
            $sale_records[$key]['goods_attr'] = $attr;
        }


        //推荐专区
        $recommends = model('Goods')
            ->field('goods_id,goods_name,goods_thums,sale_count,praise_percentage')
            ->with(['goodsPrice'=>function($query){
                $query->field('id as price_id,goods_id,campaign_price,price,attrs_values');
            }])
            ->where('store_id',$this->store_recommend)
            ->order('create_time desc')
            ->limit(2)
            ->select();
        $recommends = model('Goods')->get_attr_goods($recommends);


        //销量排行
        $top_sale = model('Goods')
            ->field('goods_id,goods_name,goods_thums,sale_count,praise_percentage')
            ->with(['goodsPrice'=>function($query){
                $query->field('id as price_id,goods_id,campaign_price,price,attrs_values');
            }])
            ->order('sale_count desc')
            ->find();
        $goods_price = $top_sale['goods_price'][0];
        unset($top_sale['goods_price']);
        $goods_price['attrs_values'] =  model('Goods')->get_four_attr($goods_price['attrs_values']);
        $top_sale['goodsPrice'] = $goods_price;

        //人气排行
        $top_click = model('Goods')
            ->field('goods_id,goods_name,goods_thums,sale_count,praise_percentage,look_num')
            ->with(['goodsPrice'=>function($query){
                $query->field('id as price_id,goods_id,campaign_price,price,attrs_values');
            }])
            ->order('look_num desc')
            ->find();
        $goods_price = $top_click['goods_price'][0];
        unset($top_click['goods_price']);
        $goods_price['attrs_values'] =  model('Goods')->get_four_attr($goods_price['attrs_values']);
        $top_click['goodsPrice'] = $goods_price;

        $data = [
            'banner_tops'   =>$banner_tops,
            'headlines'     =>$headlines,
            'fans'          =>$fans,
            'banner_mids'   =>$banner_mids,
            'good_comments' =>$good_comments,
            'specials'      =>$specials,
            'sale_records'  =>$sale_records,
            'recommends'    =>$recommends,
            'top_sale'      =>$top_sale,
            'top_click'     =>$top_click
        ];


        if($api){
            return json(apiSuccess($data));
        }else{
            return view($data);
        }

    }

    public function search($api = false){
        if(request()->isPost()){
            //每页条数
            $per_page = input('per_page','5');
            //第几页，默认第一页
            $page  = input('page','1');

            $attr = model('Goods_attr')
                ->field('attr_id,value')
                ->find($this->attr_capacity);
            $attr_capacity['attr_id'] = $attr['attr_id'];
            $attr = unserialize($attr['value']);
            $k = 0;
            foreach ($attr  as $key => $value){
                $attr_capacity['capacity'][$k] = $value['value'];
                $k++;
            }
            unset($attr);

            $stores = model('storeInfo')
                ->field('id,store_name')
                ->where('is_using','Y')
                ->select();

            $search_name = input('search_name');
            if(!empty($search_name)){
                $goods = model('Goods')
                    ->alias('a')
                    ->field('a.goods_id,a.goods_thums,a.goods_name,a.market_price,a.shop_price,c.brand_name,d.name')
                    ->with(['capacity'=>function($query){
                        $query->field('goods_id,value')->where('attr_id','in',[$this->attr_capacity,$this->attr_color,$this->attr_like,$this->attr_net])->order('attr_id');
                    }])
                    ->join('ui_goods_brand c ',' a.brand_id = c.brand_id')
                    ->join('ui_brand_model d ','a.model_id = d.model_id')
                    ->where(function($query)use($search_name){
                        $query->where('c.brand_name','like','%'.$search_name.'%')->whereOr('d.name','like','%'.$search_name.'%');
                    })
                    ->limit($per_page)
                    ->page($page)
                    ->select();
            }

            $data = array(
                'capacity'  => $attr_capacity,
                'stores'    => $stores,
                'goods'     => $goods
            );

            if($api){
                return json(apiSuccess($data));
            }else{
                return view(['data'=>$data]);
            }

        }
    }


}