<?php
/**
 * Created by tiway
 * Date: 2017/9/25
 * Time: 13:58
 */

namespace app\mobile\controller;


use app\common\controller\MobileBase;

class Integral extends MobileBase
{
    private $article_integral;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->article_integral = 2; //积分类型

    }

    /**
     * @desc 积分列表（支出/收入）
     * @param bool $api
     * @return \think\response\Json|\think\response\View
     */
    public function integral_list($api = false){
        if(request()->isPost()){
            if(empty($this->user_id))
                return json(apiSessionFail());

            $type = input('type',1);
            $integral_list = model('Integral')->getIntegralList($this->user_id,$type);
            if($api){
                return json(apiSuccess($integral_list));
            }else{
                return view(['integral_list'=>$integral_list]);
            }

        }

    }

}