<?php
/**
 * Created by tiway
 * Date: 2017/9/25
 * Time: 10:50
 */

namespace app\mobile\controller;


use app\common\controller\MobileBase;

class Message extends MobileBase
{
    private $article_read,$article_deleted,$article_sys,$article_integral,$article_help;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->article_read     = 'read';
        $this->article_deleted  = 'deleted';
        $this->article_sys      = 1;
        $this->article_integral = 2;
        $this->article_help     = 3;

    }

    /**
     * 系统信息/帮助中心 文章详情
     * @param $article_id
     */
    public function msg_detail($article_id){
        $article = model('article')->find($article_id);
    }

}