<?php
/**
 * Created by tiway
 * Date: 2017/10/18
 * Time: 17:38
 */

namespace app\mobile\controller;


use app\common\controller\MobileBase;
use think\Exception;


class Register extends MobileBase
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub

    }

    /**
     * @desc 第一次登录能收实现自动注册
     * @param bool $api
     * @return \think\response\Json
     */
    public function login($api = false)
    {
//        if (request()->isPost()) {
            try {
                $mobile = input('mobile');
                $code = input('code');
                $parent_id = input('parent_id',0);
                if ($api == false)
                    throw new Exception('非法入口');
                if (!preg_match("/^1[34578]\d{9}$/", $mobile))
                    throw new Exception('请填写正确手机号码');

                //验证码验证
                $code_info = session('smscode');

                if($code_info['mobile'] != $mobile)
                    throw new Exception('手机号码不匹配');
                if($code_info['code'] != $code)
                    throw new Exception('验证码错误，请重新获取短信验证码');

                //是否存在该手机号码用户
                $user = model('User')->field('user_id,nickname,photo,phone')->where('phone', $mobile)->find();
                if (!empty($user)) {
                    $user_id = $user['user_id'];
                } else {
                    $user_data = array(
                        'nickname' => '游客' . rand(1000, 9999),
                        'photo' => '/user/default.jpg',
                        'phone' => $mobile,
                        'last_login_time' => time()
                    );
                    $user = new \app\common\model\User();
                    $user->save($user_data);
                    $user_id = $user->user_id;
                    if (empty($user_id))
                        throw new Exception('网络繁忙');

                    //赠送新用户注册积分
                    $integral_new = model('Config')->get_newuser_integral();
                    $integral_model = new \app\common\model\Integral();
                    $list[]  = array(
                        'user_id'   => $user_id,
                        'integral'  => $integral_new,
                        'remark'    => '新用户注册积分',
                    );

                    //给邀请好友添加积分
                    if(!empty($parent_id)){
                        //赠送积分
                        $integral = model('Config')->get_register_integral();
                        $list[] = array(
                            'user_id'   => $parent_id,
                            'integral'  => $integral,
                            'remark'    => '邀请好友赠送',
                        );
                    }
                    $integral_model->saveAll($list);

                }
                //用户session
                session('user_id', $user_id);

                return json([
                    'code' => 200,
                    'msg' => '登陆成功',
                ]);

            } catch (\Exception $e) {
                return json(apiFail($e->getMessage()));
            }
        }

//    }


    /**
     * @desc 判断是否为登录态
     * @param bool $api
     * @return \think\response\Json
     */
    public function is_need_login($api = false){
        if(request()->isPost()){
            $user_id = session('user_id');
            if(empty($user_id))
                return json(apiSessionFail());
        }

    }

    /**
     * @desc 登出
     * @return \think\response\Json
     */
    public function logout(){
        if(request()->isPost()){
            session('user_id',null);
            return json(apiSessionFail());
        }
    }


}